### ISSUE TITLE
Add Single Listing Page

### ISSUE THREAD

**Issue by moshthepitt** [moshthepitt/nomad-magazine-theme#1]
Needs to look like:

![nomad new](https://user-images.githubusercontent.com/372073/40319253-3160266c-5d30-11e8-9895-f4a148ac0a60.png)

**Comment by DavidOlilo** [comment]
![nomad single listing mockup](https://user-images.githubusercontent.com/39512548/40655571-684fab82-634a-11e8-8464-743b0af50585.png)
